In [3]:
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')
from tqdm import tqdm
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [23]:
data = pd.read_csv('C:/Users/User/Downloads/train.csv/train.csv')
labels  = pd.read_csv('C:/Users/User/Downloads/train_labels.csv/train_labels.csv')

In [24]:
data = data.iloc[:500000]
print(labels.shape)
#labels = labels.iloc[:data.shape[0]]
print(data.shape)
print(labels.shape)
data.head()

(424116, 2)
(500000, 20)
(424116, 2)


session_id  index  elapsed_time      event_name   name  level  page  \
0  20090312431273200      0             0  cutscene_click  basic      0   NaN   
1  20090312431273200      1          1323    person_click  basic      0   NaN   
2  20090312431273200      2           831    person_click  basic      0   NaN   
3  20090312431273200      3          1147    person_click  basic      0   NaN   
4  20090312431273200      4          1863    person_click  basic      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  hover_duration  \
0  -413.991405  -159.314686          380.0          494.0             NaN   
1  -413.991405  -159.314686          380.0          494.0             NaN   
2  -413.991405  -159.314686          380.0          494.0             NaN   
3  -413.991405  -159.314686          380.0          494.0             NaN   
4  -412.991405  -159.314686          381.0          494.0             NaN   

                            text    fqid                       room_fqid  \
0                      undefined   intro  tunic.historicalsociety.closet   
1  Whatcha doing over there, Jo?  gramps  tunic.historicalsociety.closet   
2         Just talking to Teddy.  gramps  tunic.historicalsociety.closet   
3     I gotta run to my meeting!  gramps  tunic.historicalsociety.closet   
4            Can I come, Gramps?  gramps  tunic.historicalsociety.closet   

                                           text_fqid  fullscreen  hq  music  \
0               tunic.historicalsociety.closet.intro           0   0      1   
1  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
2  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
3  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
4  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   

  level_group  
0         0-4  
1         0-4  
2         0-4  
3         0-4  
4         0-4

By observation it is observed that these columns fullscreen       
hq                
music             
have no variance so we can remove these columns too

In [25]:
data.drop('hq',axis = 1, inplace = True)
data.drop('fullscreen',axis = 1, inplace = True)
data.drop('music',axis = 1, inplace = True)
data.drop('text',axis = 1, inplace = True)

In [26]:
for s in data['session_id'].unique():
    #print(s)
    #print(data[data['session_id'] == s])
    print(data[data['session_id'] == s].var())
    print('--------------------------------------------------------------')
    

session_id        8.074765e+04
index             7.562528e+04
elapsed_time      1.712676e+11
level             4.212566e+01
page                       NaN
room_coor_x       2.633165e+05
room_coor_y       3.738357e+04
screen_coor_x     5.006551e+04
screen_coor_y     1.149804e+04
hover_duration    2.848928e+06
dtype: float64
--------------------------------------------------------------
session_id        2.747260e+05
index             2.941020e+05
elapsed_time      1.325226e+12
level             3.001211e+01
page              2.420807e+00
room_coor_x       2.441964e+05
room_coor_y       4.748678e+04
screen_coor_x     6.483267e+04
screen_coor_y     1.746326e+04
hover_duration    3.848555e+06
dtype: float64
--------------------------------------------------------------
session_id        8.475181e+03
index             6.140418e+04
elapsed_time      1.039048e+11
level             4.575606e+01
page              2.157258e+00
room_coor_x       2.976952e+05
room_coor_y       4.643953e+04
screen_

session_id        1.666538e+05
index             7.456885e+04
elapsed_time      1.339375e+11
level             4.409640e+01
page              0.000000e+00
room_coor_x       2.520671e+05
room_coor_y       3.374904e+04
screen_coor_x     5.119846e+04
screen_coor_y     1.269990e+04
hover_duration    3.293624e+06
dtype: float64
--------------------------------------------------------------
session_id        9.253633e+04
index             5.871874e+04
elapsed_time      3.845878e+11
level             4.283094e+01
page              5.618227e+00
room_coor_x       2.529806e+05
room_coor_y       5.747443e+04
screen_coor_x     5.168405e+04
screen_coor_y     1.827924e+04
hover_duration    7.859970e+06
dtype: float64
--------------------------------------------------------------
session_id        1.212313e+05
index             8.728738e+04
elapsed_time      1.688442e+11
level             4.162797e+01
page              4.482759e+00
room_coor_x       2.067980e+05
room_coor_y       4.255605e+04
screen_

session_id        0.000000e+00
index             8.628821e+04
elapsed_time      3.473785e+11
level             4.114515e+01
page              7.285714e+00
room_coor_x       2.646899e+05
room_coor_y       3.906850e+04
screen_coor_x     5.280670e+04
screen_coor_y     1.383004e+04
hover_duration    1.131198e+07
dtype: float64
--------------------------------------------------------------
session_id        9.741323e+04
index             1.855310e+05
elapsed_time      2.322465e+11
level             3.724939e+01
page              2.432749e+00
room_coor_x       2.929131e+05
room_coor_y       6.340494e+04
screen_coor_x     4.993063e+04
screen_coor_y     1.661782e+04
hover_duration    3.581361e+06
dtype: float64
--------------------------------------------------------------
session_id        1.539262e+04
index             8.286010e+04
elapsed_time      1.335716e+13
level             3.997766e+01
page              7.000000e-01
room_coor_x       2.357379e+05
room_coor_y       5.103090e+04
screen_

session_id        2.074898e+04
index             2.399626e+05
elapsed_time      7.590342e+11
level             4.184976e+01
page              0.000000e+00
room_coor_x       2.695203e+05
room_coor_y       5.440089e+04
screen_coor_x     5.850743e+04
screen_coor_y     1.571633e+04
hover_duration             NaN
dtype: float64
--------------------------------------------------------------
session_id        3.242571e+04
index             1.474162e+05
elapsed_time      3.137574e+11
level             3.920537e+01
page              4.284460e+00
room_coor_x       2.611694e+05
room_coor_y       4.880297e+04
screen_coor_x     5.453468e+04
screen_coor_y     1.612534e+04
hover_duration    2.863911e+06
dtype: float64
--------------------------------------------------------------
session_id        1.537968e+05
index             1.266464e+05
elapsed_time      8.339788e+11
level             4.428473e+01
page              4.008097e+00
room_coor_x       3.532744e+05
room_coor_y       4.443796e+04
screen_

session_id        3.844958e+04
index             1.214904e+05
elapsed_time      1.354139e+12
level             4.139612e+01
page              3.545907e+00
room_coor_x       2.470805e+05
room_coor_y       5.200515e+04
screen_coor_x     5.772368e+04
screen_coor_y     1.976689e+04
hover_duration    3.465093e+06
dtype: float64
--------------------------------------------------------------
session_id        7.626924e+04
index             6.545801e+04
elapsed_time      1.837625e+11
level             4.222282e+01
page                       NaN
room_coor_x       3.009272e+05
room_coor_y       3.356771e+04
screen_coor_x     6.164863e+04
screen_coor_y     1.215740e+04
hover_duration    3.285872e+06
dtype: float64
--------------------------------------------------------------
session_id        7.406313e+04
index             8.396214e+04
elapsed_time      3.776544e+12
level             4.353353e+01
page              4.235294e+00
room_coor_x       2.740977e+05
room_coor_y       4.332583e+04
screen_

session_id        1.255123e+04
index             2.740638e+05
elapsed_time      5.430762e+11
level             3.979800e+01
page              4.428571e+00
room_coor_x       2.667067e+05
room_coor_y       4.287742e+04
screen_coor_x     6.656168e+04
screen_coor_y     1.568591e+04
hover_duration    2.323755e+06
dtype: float64
--------------------------------------------------------------
session_id        5.779953e+03
index             1.939742e+05
elapsed_time      7.505263e+11
level             3.622387e+01
page              0.000000e+00
room_coor_x       2.719258e+05
room_coor_y       4.681331e+04
screen_coor_x     5.791093e+04
screen_coor_y     1.674883e+04
hover_duration    2.816434e+06
dtype: float64
--------------------------------------------------------------
session_id        1.239939e+05
index             1.724926e+05
elapsed_time      5.759710e+11
level             3.678774e+01
page              4.946218e+00
room_coor_x       2.737066e+05
room_coor_y       5.028773e+04
screen_

session_id        1.666086e+05
index             1.235077e+05
elapsed_time      5.303453e+11
level             4.381838e+01
page              4.460386e+00
room_coor_x       2.736918e+05
room_coor_y       4.532283e+04
screen_coor_x     5.580963e+04
screen_coor_y     1.239955e+04
hover_duration    8.313917e+06
dtype: float64
--------------------------------------------------------------
session_id        5.302069e+05
index             5.087978e+05
elapsed_time      5.121887e+12
level             4.418877e+01
page              4.292456e+00
room_coor_x       2.301331e+05
room_coor_y       3.670806e+04
screen_coor_x     5.751003e+04
screen_coor_y     1.675869e+04
hover_duration    2.763456e+06
dtype: float64
--------------------------------------------------------------
session_id        9.497788e+04
index             6.885561e+04
elapsed_time      5.728342e+11
level             4.488638e+01
page              0.000000e+00
room_coor_x       2.488568e+05
room_coor_y       4.929657e+04
screen_

session_id        5.186206e+05
index             4.860181e+05
elapsed_time      4.236912e+12
level             4.050695e+01
page              3.509079e+00
room_coor_x       2.149149e+05
room_coor_y       4.388040e+04
screen_coor_x     5.330432e+04
screen_coor_y     1.824547e+04
hover_duration    2.757920e+06
dtype: float64
--------------------------------------------------------------
session_id        2.961315e+04
index             1.008441e+05
elapsed_time      3.182755e+11
level             4.271513e+01
page              2.571429e+00
room_coor_x       2.800797e+05
room_coor_y       4.447198e+04
screen_coor_x     6.288289e+04
screen_coor_y     1.370147e+04
hover_duration    5.117934e+06
dtype: float64
--------------------------------------------------------------
session_id        1.961249e+04
index             2.232715e+05
elapsed_time      1.208678e+12
level             3.948653e+01
page              3.238095e+00
room_coor_x       2.590141e+05
room_coor_y       4.947167e+04
screen_

dtype: float64
--------------------------------------------------------------
session_id        2.313177e+04
index             6.737604e+04
elapsed_time      9.891217e+10
level             4.311828e+01
page                       NaN
room_coor_x       2.652085e+05
room_coor_y       3.535760e+04
screen_coor_x     5.019682e+04
screen_coor_y     1.161535e+04
hover_duration    5.425271e+06
dtype: float64
--------------------------------------------------------------
session_id        9.998337e+04
index             5.981193e+04
elapsed_time      1.423094e+11
level             4.106368e+01
page              5.151515e-01
room_coor_x       2.611266e+05
room_coor_y       4.739931e+04
screen_coor_x     4.942558e+04
screen_coor_y     1.654767e+04
hover_duration    2.018267e+06
dtype: float64
--------------------------------------------------------------
session_id        3.538949e+04
index             6.052848e+04
elapsed_time      1.829756e+11
level             4.517915e+01
page              4.15

session_id        3.651218e+05
index             1.305145e+05
elapsed_time      2.519963e+11
level             3.876968e+01
page              3.410000e+00
room_coor_x       3.056031e+05
room_coor_y       6.335865e+04
screen_coor_x     5.642288e+04
screen_coor_y     1.572597e+04
hover_duration    1.118446e+07
dtype: float64
--------------------------------------------------------------
session_id        4.669064e+04
index             1.651735e+05
elapsed_time      2.242357e+11
level             3.676739e+01
page                       NaN
room_coor_x       2.788259e+05
room_coor_y       5.901038e+04
screen_coor_x     5.569374e+04
screen_coor_y     1.468518e+04
hover_duration    3.842901e+06
dtype: float64
--------------------------------------------------------------
session_id        4.844130e+04
index             1.338981e+05
elapsed_time      2.661374e+11
level             5.033526e+01
page              5.867647e+00
room_coor_x       2.792494e+05
room_coor_y       4.253707e+04
screen_

session_id        1.024969e+03
index             1.036646e+05
elapsed_time      7.341516e+11
level             4.055552e+01
page              3.978280e+00
room_coor_x       2.283876e+05
room_coor_y       4.069011e+04
screen_coor_x     5.339239e+04
screen_coor_y     1.765422e+04
hover_duration    2.301774e+06
dtype: float64
--------------------------------------------------------------
session_id        4.845321e+05
index             1.507079e+06
elapsed_time      1.668204e+12
level             4.110642e+01
page              3.698889e+00
room_coor_x       2.528317e+05
room_coor_y       3.591865e+04
screen_coor_x     5.662206e+04
screen_coor_y     1.417835e+04
hover_duration    2.626478e+06
dtype: float64
--------------------------------------------------------------
session_id        3.137363e+03
index             4.690946e+05
elapsed_time      9.170301e+11
level             3.508317e+01
page              2.504878e+00
room_coor_x       3.119031e+05
room_coor_y       3.617186e+04
screen_

session_id        1.212345e+05
index             8.245435e+04
elapsed_time      2.970804e+11
level             4.269819e+01
page              4.966154e+00
room_coor_x       2.784671e+05
room_coor_y       5.006296e+04
screen_coor_x     5.420232e+04
screen_coor_y     1.372186e+04
hover_duration    1.070640e+07
dtype: float64
--------------------------------------------------------------
session_id        1.025025e+03
index             9.330127e+04
elapsed_time      8.321688e+12
level             3.607785e+01
page              2.266667e+00
room_coor_x       2.741584e+05
room_coor_y       3.865020e+04
screen_coor_x     4.957043e+04
screen_coor_y     1.444830e+04
hover_duration    2.511018e+06
dtype: float64
--------------------------------------------------------------
session_id        3.699773e+05
index             1.295318e+05
elapsed_time      6.943395e+11
level             4.061420e+01
page              9.600000e+00
room_coor_x       2.926758e+05
room_coor_y       4.860214e+04
screen_

session_id        3.243484e+04
index             8.339256e+04
elapsed_time      3.829565e+11
level             4.575480e+01
page                       NaN
room_coor_x       2.588605e+05
room_coor_y       4.200886e+04
screen_coor_x     4.778205e+04
screen_coor_y     1.303256e+04
hover_duration    1.351485e+07
dtype: float64
--------------------------------------------------------------
session_id        1.268889e+05
index             6.602796e+04
elapsed_time      2.212223e+11
level             4.069396e+01
page              2.839406e+00
room_coor_x       2.433896e+05
room_coor_y       5.360310e+04
screen_coor_x     5.592300e+04
screen_coor_y     1.901123e+04
hover_duration    1.237852e+07
dtype: float64
--------------------------------------------------------------
session_id        1.415248e+05
index             8.793611e+04
elapsed_time      1.400985e+13
level             4.310191e+01
page              2.733333e+00
room_coor_x       2.701348e+05
room_coor_y       4.444196e+04
screen_

session_id        3.244985e+04
index             4.122121e+04
elapsed_time      3.629014e+11
level             4.373588e+01
page                       NaN
room_coor_x       2.397147e+05
room_coor_y       4.444727e+04
screen_coor_x     4.756450e+04
screen_coor_y     1.369096e+04
hover_duration    6.483329e+06
dtype: float64
--------------------------------------------------------------
session_id        7.062000e+03
index             1.257995e+05
elapsed_time      6.373427e+11
level             3.726288e+01
page              3.578947e+00
room_coor_x       2.652458e+05
room_coor_y       4.748634e+04
screen_coor_x     5.671228e+04
screen_coor_y     1.603729e+04
hover_duration    3.811181e+09
dtype: float64
--------------------------------------------------------------
session_id        1.347080e+04
index             8.414517e+04
elapsed_time      4.586482e+14
level             3.780992e+01
page              3.000000e+00
room_coor_x       2.897768e+05
room_coor_y       5.302597e+04
screen_

session_id        4.671597e+04
index             5.867044e+04
elapsed_time      4.525970e+11
level             4.265766e+01
page              2.957672e+00
room_coor_x       2.649409e+05
room_coor_y       4.461826e+04
screen_coor_x     5.736691e+04
screen_coor_y     1.728997e+04
hover_duration    1.391576e+07
dtype: float64
--------------------------------------------------------------
session_id        1.539522e+04
index             6.349296e+04
elapsed_time      1.224300e+11
level             4.195451e+01
page              0.000000e+00
room_coor_x       2.455993e+05
room_coor_y       4.537296e+04
screen_coor_x     4.404412e+04
screen_coor_y     1.470149e+04
hover_duration    7.674614e+06
dtype: float64
--------------------------------------------------------------
session_id        1.851773e+04
index             7.074889e+04
elapsed_time      3.041363e+11
level             4.257573e+01
page              4.168421e+00
room_coor_x       2.671543e+05
room_coor_y       4.410273e+04
screen_

session_id        1.476000e+05
index             9.840376e+04
elapsed_time      1.393076e+11
level             4.633397e+01
page              5.076923e+00
room_coor_x       2.869188e+05
room_coor_y       4.346003e+04
screen_coor_x     5.054771e+04
screen_coor_y     1.889393e+04
hover_duration    6.563111e+06
dtype: float64
--------------------------------------------------------------
session_id        9.743566e+04
index             1.042299e+05
elapsed_time      1.480157e+12
level             4.638276e+01
page              4.922764e+00
room_coor_x       2.664634e+05
room_coor_y       5.382294e+04
screen_coor_x     6.108354e+04
screen_coor_y     1.990286e+04
hover_duration    7.226915e+06
dtype: float64
--------------------------------------------------------------
session_id        1.130515e+05
index             5.238970e+04
elapsed_time      2.073367e+11
level             4.114815e+01
page                       NaN
room_coor_x       2.575962e+05
room_coor_y       4.067199e+04
screen_

session_id        2.080390e+05
index             3.649763e+05
elapsed_time      9.015024e+11
level             3.914162e+01
page              4.723137e+00
room_coor_x       2.395209e+05
room_coor_y       5.098242e+04
screen_coor_x     6.259019e+04
screen_coor_y     1.725946e+04
hover_duration    5.697906e+06
dtype: float64
--------------------------------------------------------------
session_id        3.100704e+04
index             9.586517e+04
elapsed_time      4.005026e+11
level             4.055679e+01
page              3.485450e+00
room_coor_x       2.366018e+05
room_coor_y       5.147825e+04
screen_coor_x     4.979215e+04
screen_coor_y     1.467464e+04
hover_duration    4.642775e+06
dtype: float64
--------------------------------------------------------------
session_id        2.344729e+05
index             1.092991e+05
elapsed_time      2.387465e+12
level             4.295098e+01
page                       NaN
room_coor_x       2.323435e+05
room_coor_y       3.550538e+04
screen_

In [27]:
data['event_name'] = data['event_name'].astype('category').cat.codes
data['name'] = data['name'].astype('category').cat.codes
data['text_fqid'] = data['text_fqid'].astype('category').cat.codes
data['room_fqid'] = data['room_fqid'].astype('category').cat.codes
data['fqid'] = data['fqid'].astype('category').cat.codes
data['level_group'] = data['level_group'].astype('category').cat.codes

In [28]:
labels['session'] = labels.session_id.apply(lambda x: int(x.split('_')[0]) )
labels['q'] = labels.session_id.apply(lambda x: int(x.split('_')[-1][1:]) )

In [29]:
labels.drop('session_id',axis = 1, inplace = True)

In [30]:
#print(labels[labels['session']== 22000610592348800])
labels.head(20)

correct            session  q
0         1  20090312431273200  1
1         0  20090312433251036  1
2         1  20090312455206810  1
3         0  20090313091715820  1
4         1  20090313571836404  1
5         1  20090314035813970  1
6         1  20090314121766812  1
7         0  20090314221187252  1
8         1  20090314363702160  1
9         1  20090314441803444  1
10        0  20090315081004164  1
11        1  20090315085850788  1
12        1  20090315101457836  1
13        1  20090315170769824  1
14        0  20090315270479452  1
15        1  20090316152177500  1
16        1  20090316190523732  1
17        0  20090317080721164  1
18        1  20090317111400710  1
19        1  20090317414400068  1

In [31]:
#print(data.head())

#original_labels = pd.DataFrame(columns = ['correct']) 
#for q in (labels.q.unique()):
    #questions = pd.DataFrame() 
   # for session in tqdm(data['session_id']):
        #print(session)
        #questions.append(labels[(labels['session'] == session) & (labels['q'] == q)])
        #questions.append(labels[(labels['session'] == session) & (labels['q'] == q)].q.loc[0,0])
        #print(labels[(labels['session'] == session) & (labels['q'] == q)]['correct'])
       # questions = questions.append(labels[(labels['session'] == session) & (labels['q'] == q)]['correct'])
        
    #original_labels = pd.concat([original_labels,questions],axis = 1)
    #original_labels.describe
    #break


In [32]:
sessions = data.session_id.value_counts().reset_index()
sessions.columns = ['id','count']
print(sessions)

                    id  count
0    20100114224046390   4174
1    20100017221780384   3114
2    20100111522448010   2780
3    20100118090535520   2776
4    20100109470804544   2737
..                 ...    ...
438  20100210333994556    697
439  20100209514133092    664
440  20100111111155972    655
441  20100119192145600    651
442  20100211430371096     29

[443 rows x 2 columns]


Preparing the data, since each session involves 18 individual questions, lets create a model that trains and generates response for all the questions.

In [33]:
#del original_labels
y = pd.DataFrame()
for Session_count in sessions.iterrows():
    label = labels[labels['session'] ==  Session_count[1]['id']][['q','correct']]
    questions = pd.DataFrame({'session' : [Session_count[1]['id']]})
    for que in label.iterrows():
        questions['que' + str(que[1]['q'])] = [que[1]['correct']]
    #print   
    y =  pd.concat([y,questions], ignore_index=True)
    print(y.shape)
    
    #temp = pd.DataFrame('session' = [Session_count[1]['id']], 'correct' = [])
    #y = pd.concat()
del labels   

(1, 19)
(2, 19)
(3, 19)
(4, 19)
(5, 19)
(6, 19)
(7, 19)
(8, 19)
(9, 19)
(10, 19)
(11, 19)
(12, 19)
(13, 19)
(14, 19)
(15, 19)
(16, 19)
(17, 19)
(18, 19)
(19, 19)
(20, 19)
(21, 19)
(22, 19)
(23, 19)
(24, 19)
(25, 19)
(26, 19)
(27, 19)
(28, 19)
(29, 19)
(30, 19)
(31, 19)
(32, 19)
(33, 19)
(34, 19)
(35, 19)
(36, 19)
(37, 19)
(38, 19)
(39, 19)
(40, 19)
(41, 19)
(42, 19)
(43, 19)
(44, 19)
(45, 19)
(46, 19)
(47, 19)
(48, 19)
(49, 19)
(50, 19)
(51, 19)
(52, 19)
(53, 19)
(54, 19)
(55, 19)
(56, 19)
(57, 19)
(58, 19)
(59, 19)
(60, 19)
(61, 19)
(62, 19)
(63, 19)
(64, 19)
(65, 19)
(66, 19)
(67, 19)
(68, 19)
(69, 19)
(70, 19)
(71, 19)
(72, 19)
(73, 19)
(74, 19)
(75, 19)
(76, 19)
(77, 19)
(78, 19)
(79, 19)
(80, 19)
(81, 19)
(82, 19)
(83, 19)
(84, 19)
(85, 19)
(86, 19)
(87, 19)
(88, 19)
(89, 19)
(90, 19)
(91, 19)
(92, 19)
(93, 19)
(94, 19)
(95, 19)
(96, 19)
(97, 19)
(98, 19)
(99, 19)
(100, 19)
(101, 19)
(102, 19)
(103, 19)
(104, 19)
(105, 19)
(106, 19)
(107, 19)
(108, 19)
(109, 19)
(110, 19)
(111, 19

In [34]:
data = pd.merge(data, y, left_on = 'session_id',right_on='session', how='inner')
data.shape

(500000, 35)

In [35]:
data.head()

session_id  index  elapsed_time  event_name  name  level  page  \
0  20090312431273200      0             0           1     0      0   NaN   
1  20090312431273200      1          1323          10     0      0   NaN   
2  20090312431273200      2           831          10     0      0   NaN   
3  20090312431273200      3          1147          10     0      0   NaN   
4  20090312431273200      4          1863          10     0      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  ...  que9  que10  que11  que12  \
0  -413.991405  -159.314686          380.0  ...     1      1      1      1   
1  -413.991405  -159.314686          380.0  ...     1      1      1      1   
2  -413.991405  -159.314686          380.0  ...     1      1      1      1   
3  -413.991405  -159.314686          380.0  ...     1      1      1      1   
4  -412.991405  -159.314686          381.0  ...     1      1      1      1   

   que13  que14  que15  que16  que17  que18  
0      0      1      1      0      1      1  
1      0      1      1      0      1      1  
2      0      1      1      0      1      1  
3      0      1      1      0      1      1  
4      0      1      1      0      1      1  

[5 rows x 35 columns]

In [36]:
questions = pd.DataFrame()
questions['que1'] = data['que1']
data.drop('que1',axis=1,inplace=True)
questions['que2'] = data['que2']
data.drop('que2',axis=1,inplace=True)
questions['que3'] = data['que3']
data.drop('que3',axis=1,inplace=True)
questions['que4'] = data['que4']
data.drop('que4',axis=1,inplace=True)
questions['que5'] = data['que5']
data.drop('que5',axis=1,inplace=True)
questions['que6'] = data['que6']
data.drop('que6',axis=1,inplace=True)
questions['que7'] = data['que7']
data.drop('que7',axis=1,inplace=True)
questions['que8'] = data['que8']
data.drop('que8',axis=1,inplace=True)
questions['que9'] = data['que9']
data.drop('que9',axis=1,inplace=True)
questions['que10'] = data['que10']
data.drop('que10',axis=1,inplace=True)
questions['que11'] = data['que11']
data.drop('que11',axis=1,inplace=True)
questions['que12'] = data['que12']
data.drop('que12',axis=1,inplace=True)
questions['que13'] = data['que13']
data.drop('que13',axis=1,inplace=True)
questions['que14'] = data['que14']
data.drop('que14',axis=1,inplace=True)
questions['que15'] = data['que15']
data.drop('que15',axis=1,inplace=True)
questions['que16'] = data['que16']
data.drop('que16',axis=1,inplace=True)
questions['que17'] = data['que17']
data.drop('que17',axis=1,inplace=True)
questions['que18'] = data['que18']
data.drop('que18',axis=1,inplace=True)

In [37]:
#data.drop('text', axis = 1, inplace = True)
data = data.fillna(method='ffill', axis=0)
data = data.fillna(0)


In [38]:
#print(data.head())

#data.drop('session',axis = 1, inplace = True)
#data.drop('index',axis = 1, inplace = True)
print(data['page'].value_counts())
for c in data.columns:
    print(data[c][:3])

6.0    117436
5.0     76724
1.0     76530
4.0     70346
0.0     67828
3.0     56455
2.0     34681
Name: page, dtype: int64
0    20090312431273200
1    20090312431273200
2    20090312431273200
Name: session_id, dtype: int64
0    0
1    1
2    2
Name: index, dtype: int64
0       0
1    1323
2     831
Name: elapsed_time, dtype: int64
0     1
1    10
2    10
Name: event_name, dtype: int8
0    0
1    0
2    0
Name: name, dtype: int8
0    0
1    0
2    0
Name: level, dtype: int64
0    0.0
1    0.0
2    0.0
Name: page, dtype: float64
0   -413.991405
1   -413.991405
2   -413.991405
Name: room_coor_x, dtype: float64
0   -159.314686
1   -159.314686
2   -159.314686
Name: room_coor_y, dtype: float64
0    380.0
1    380.0
2    380.0
Name: screen_coor_x, dtype: float64
0    494.0
1    494.0
2    494.0
Name: screen_coor_y, dtype: float64
0    0.0
1    0.0
2    0.0
Name: hover_duration, dtype: float64
0    40
1    37
2    37
Name: fqid, dtype: int16
0    7
1    7
2    7
Name: room_fqid, dtype: int8
0 

Since the data has repeated features (Session, session_id) we can remove one of them. Index does'nt provide a significance either so remove that too.

Seems like pages are all NaN, verify and deal with it.

In [39]:
data.drop('session',axis = 1, inplace = True)
data.drop('index',axis = 1, inplace = True)
data.head()

session_id  elapsed_time  event_name  name  level  page  \
0  20090312431273200             0           1     0      0   0.0   
1  20090312431273200          1323          10     0      0   0.0   
2  20090312431273200           831          10     0      0   0.0   
3  20090312431273200          1147          10     0      0   0.0   
4  20090312431273200          1863          10     0      0   0.0   

   room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  hover_duration  \
0  -413.991405  -159.314686          380.0          494.0             0.0   
1  -413.991405  -159.314686          380.0          494.0             0.0   
2  -413.991405  -159.314686          380.0          494.0             0.0   
3  -413.991405  -159.314686          380.0          494.0             0.0   
4  -412.991405  -159.314686          381.0          494.0             0.0   

   fqid  room_fqid  text_fqid  level_group  
0    40          7         33            0  
1    37          7         32            0  
2    37          7         32            0  
3    37          7         32            0  
4    37          7         32            0

In [40]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier


del y
#Split data into training and testing sets
#X_train, X_test, y1_train, y1_test, y2_train, y2_test,y3_train,y3_test,y4_train,y4_test,y5_train,y5_test,y6_train,y6_test,y7_train,y7_test,y8_train,y8_test,y9_train,y9_test,y10_train,y10_test,y11_train,y11_test,y12_train,y12_test,y13_train,y13_test,y14_train,y14_test,y15_train,y15_test,y16_train,y16_test,y17_train,y17_test,y18_train,y18_test = train_test_split(data, que1, que2,que3,que4,que5,que6,que7,que8,que9,que10,que11,que12,que13,que14,que15,que16,que17,que18, test_size=0.2)
X_train, X_test, y1_train, y1_test= train_test_split(data,questions, test_size=0.2)

del data
del questions
# Define the model
model = RandomForestClassifier(random_state=1,verbose = 1)

# Define the multi-output classifier
multi_output_model = MultiOutputClassifier(model, n_jobs=-1)

# Fit the model to the training data
#multi_output_model.fit(X_train, (y1_train, y2_train,y3_train, y4_train,y5_train, y6_train,y7_train, y8_train,y9_train, y10_train,y11_train, y12_train,y13_train, y14_train,y15_train, y16_train,y17_train, y18_train))
multi_output_model.fit(X_train,y1_train)
# Predict the outputs for the test data
#y1_pred, y2_pred,y3_pred, y4_pred,y5_pred, y6_pred,y7_pred, y8_pred,y9_pred, y10_pred,y11_pred, y12_pred,y13_pred, y14_pred,y5_pred, y16_pred,y17_pred, y18_pred = multi_output_model.predict(X_test)
y1_pred = multi_output_model.predict(X_test)

# Print the predicted outputs and the corresponding true values
print("Predicted outputs:")
print("Output 1:", y1_pred) 
#print("Output 2:", y2_pred)
print("True values:")
print("Output 1:", y1_test)
#print("Output 2:", y2_test)


Predicted outputs:
Output 1: [[0 1 1 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 0 1]
 ...
 [1 1 1 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 [0 1 1 ... 1 1 1]]
True values:
Output 1:         que1  que2  que3  que4  que5  que6  que7  que8  que9  que10  que11  \
259665     0     1     1     1     0     1     1     1     0      0      0   
461409     1     1     1     1     1     1     1     0     1      1      1   
243893     1     1     1     0     0     1     1     1     0      1      1   
342268     1     1     1     1     0     1     1     1     1      1      1   
489942     0     1     0     0     0     0     0     0     0      0      0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...   
462189     1     1     1     1     1     1     1     0     1      1      1   
468944     1     1     1     0     0     1     1     0     1      0      0   
483005     1     1     1     1     1     1     1     1     1      1      0   
389962     0     1     1     0     1     0     0

In [42]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y1_test['que1'], y1_pred[:,0])
print(acc_score)

0.96244


In [43]:
test = pd.read_csv('C:/Users/User/Downloads/test.csv')

In [44]:

session_level = test[['session_level','session_id']]
print(session_level.head(1000))
test.drop('session_level',axis = 1, inplace = True)


     session_level         session_id
0                0  20090109393214576
1                0  20090109393214576
2                0  20090109393214576
3                0  20090109393214576
4                0  20090109393214576
..             ...                ...
995              2  20090109393214576
996              2  20090109393214576
997              2  20090109393214576
998              2  20090109393214576
999              2  20090109393214576

[1000 rows x 2 columns]


In [45]:
def data_ready(test):
    test.drop('hq',axis = 1, inplace = True)
    test.drop('fullscreen',axis = 1, inplace = True)
    test.drop('music',axis = 1, inplace = True)
    test.drop('text',axis = 1, inplace = True)
    test.drop('index',axis = 1, inplace = True)
    #labels to categories
    test['event_name'] = test['event_name'].astype('category').cat.codes
    test['name'] = test['name'].astype('category').cat.codes
    test['text_fqid'] = test['text_fqid'].astype('category').cat.codes
    test['room_fqid'] = test['room_fqid'].astype('category').cat.codes
    test['fqid'] = test['fqid'].astype('category').cat.codes
    test['level_group'] = test['level_group'].astype('category').cat.codes
    test = test.fillna(method='ffill', axis=0)
    test = test.fillna(0)
    print(X_test.columns)
    print(test.columns)
    pred = multi_output_model.predict(test)
    
    
    
    
    return pred


pred = data_ready(test)
print(pred)

Index(['session_id', 'elapsed_time', 'event_name', 'name', 'level', 'page',
       'room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y',
       'hover_duration', 'fqid', 'room_fqid', 'text_fqid', 'level_group'],
      dtype='object')
Index(['session_id', 'elapsed_time', 'event_name', 'name', 'level', 'page',
       'room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y',
       'hover_duration', 'fqid', 'room_fqid', 'text_fqid', 'level_group'],
      dtype='object')
[[1 1 1 ... 0 1 1]
 [1 1 1 ... 0 1 1]
 [1 1 1 ... 0 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 0 1]]


In [46]:
def setting_data():
    pass

pred = pd.DataFrame(pred)
pred['session_id'] = test['session_id']
pred = pd.merge(pred,session_level, on= 'session_id')
print(pred.shape)
print(test.shape)
print(pred.head())

(4776870, 20)
(3728, 15)
   0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  \
0  1  1  1  1  1  1  1  1  1  1   1   1   0   1   1   0   1   1   
1  1  1  1  1  1  1  1  1  1  1   1   1   0   1   1   0   1   1   
2  1  1  1  1  1  1  1  1  1  1   1   1   0   1   1   0   1   1   
3  1  1  1  1  1  1  1  1  1  1   1   1   0   1   1   0   1   1   
4  1  1  1  1  1  1  1  1  1  1   1   1   0   1   1   0   1   1   

          session_id  session_level  
0  20090109393214576              0  
1  20090109393214576              0  
2  20090109393214576              0  
3  20090109393214576              0  
4  20090109393214576              0  


In [47]:

print(type(pred))

<class 'pandas.core.frame.DataFrame'>


In [48]:
submission = pd.DataFrame({'session_id':[] , 'correct' : [] })
for session_id in tqdm(pred['session_id'].unique()):
    temp1 = pred[pred['session_id'] == session_id]
    for level in temp1['session_level'].unique():
        temp = temp1[temp1['session_level'] == level]
        ques_dic = {}
        for i in range(0,18):
            ques_dic['q' + str(i+1)] = temp[i].mode()[0]
        #level = temp['session_level'].mode()[0]
        #print(ques_dic)
        sub = pd.DataFrame({'session_id':[] , 'correct' : [] , 'session_level' : []})
        for i,j in ques_dic.items():
            sub['session_id'] = [str(session_id) + '_' + i]
            sub['correct'] = [int(ques_dic[i])]
            sub['session_level'] = level
            #print(sub)
            submission = pd.concat([submission,sub], axis = 0)
    

print(submission.head())
test.head()            

100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.28it/s]

             session_id  correct  session_level
0  20090109393214576_q1      1.0            0.0
0  20090109393214576_q2      1.0            0.0
0  20090109393214576_q3      1.0            0.0
0  20090109393214576_q4      1.0            0.0
0  20090109393214576_q5      0.0            0.0


session_id  elapsed_time  event_name  name  level  page  \
0  20090109393214576             0           1     0      0   NaN   
1  20090109393214576          1965          10     0      0   NaN   
2  20090109393214576          3614          10     0      0   NaN   
3  20090109393214576          5330          10     0      0   NaN   
4  20090109393214576          6397          10     0      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  hover_duration  \
0  -413.991405    75.685314          380.0          259.0             NaN   
1  -105.991405   -63.314686          688.0          398.0             NaN   
2  -418.991405    47.685314          375.0          287.0             NaN   
3  -110.991405   -57.314686          683.0          392.0             NaN   
4  -110.991405   -57.314686          683.0          392.0             NaN   

   fqid  room_fqid  text_fqid  level_group  
0    30          7         23            0  
1    27          7         22            0  
2    27          7         22            0  
3    27          7         22            0  
4    27          7         22            0

In [49]:
print(test.shape)
print(submission.shape)

(3728, 15)
(162, 3)


In [52]:
submission.to_csv('C:/Users/User/Downloads/test.csv',index = False)